In [1]:
%matplotlib inline

In [2]:
import numpy as np
import pandas as pd
from scipy.stats import zscore
from sklearn.metrics import accuracy_score

In [3]:
import os
os.getcwd()

'C:\\Users\\sreekar chidurala\\Desktop\\unsupervised week 6\\machine_learning-master(github)'

In [6]:
# path0 = C:\Users\classroom2-DTP\Documents
wine = pd.read_csv('winedata.csv', header=-1)


In [7]:
wine.head()

0      1     2     3     4    5     6     7     8     9     10    11    12  \
0   1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1   1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2   1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3   1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4   1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [11]:
wine.shape

(178, 14)

In [12]:
wine.describe().T

count        mean         std     min       25%      50%       75%  \
0   178.0    1.938202    0.775035    1.00    1.0000    2.000    3.0000   
1   178.0   13.000618    0.811827   11.03   12.3625   13.050   13.6775   
2   178.0    2.336348    1.117146    0.74    1.6025    1.865    3.0825   
3   178.0    2.366517    0.274344    1.36    2.2100    2.360    2.5575   
4   178.0   19.494944    3.339564   10.60   17.2000   19.500   21.5000   
5   178.0   99.741573   14.282484   70.00   88.0000   98.000  107.0000   
6   178.0    2.295112    0.625851    0.98    1.7425    2.355    2.8000   
7   178.0    2.029270    0.998859    0.34    1.2050    2.135    2.8750   
8   178.0    0.361854    0.124453    0.13    0.2700    0.340    0.4375   
9   178.0    1.590899    0.572359    0.41    1.2500    1.555    1.9500   
10  178.0    5.058090    2.318286    1.28    3.2200    4.690    6.2000   
11  178.0    0.957449    0.228572    0.48    0.7825    0.965    1.1200   
12  178.0    2.611685    0.709990    1.27    1.9375    2.780    3.1700   
13  178.0  746.893258  314.907474  278.00  500.5000  673.500  985.0000   

        max  
0      3.00  
1     14.83  
2      5.80  
3      3.23  
4     30.00  
5    162.00  
6      3.88  
7      5.08  
8      0.66  
9      3.58  
10    13.00  
11     1.71  
12     4.00  
13  1680.00

In [8]:
wine_x = wine.iloc[:,1:]
wine_y = wine.iloc[:,0]

In [19]:
wine_x.head()
wine_y.head()

0    1
1    1
2    1
3    1
4    1
Name: 0, dtype: int64

In [9]:
wine_scaled = wine_x.apply(zscore)

In [10]:
wine_scaled.head()

1         2         3         4         5         6         7   \
0  1.518613 -0.562250  0.232053 -1.169593  1.913905  0.808997  1.034819   
1  0.246290 -0.499413 -0.827996 -2.490847  0.018145  0.568648  0.733629   
2  0.196879  0.021231  1.109334 -0.268738  0.088358  0.808997  1.215533   
3  1.691550 -0.346811  0.487926 -0.809251  0.930918  2.491446  1.466525   
4  0.295700  0.227694  1.840403  0.451946  1.281985  0.808997  0.663351   

         8         9         10        11        12        13  
0 -0.659563  1.224884  0.251717  0.362177  1.847920  1.013009  
1 -0.820719 -0.544721 -0.293321  0.406051  1.113449  0.965242  
2 -0.498407  2.135968  0.269020  0.318304  0.788587  1.395148  
3 -0.981875  1.032155  1.186068 -0.427544  1.184071  2.334574  
4  0.226796  0.401404 -0.319276  0.362177  0.449601 -0.037874

In [13]:
from sklearn.decomposition import PCA
pca = PCA(n_components=5)
pca.fit_transform(wine_scaled)
wine_pca = pca.fit_transform(wine_scaled)

In [14]:
# Let us investigate the proportion 
# of variance explained and the elbow method

# pca.get_covariance()
pca.explained_variance_

# len(pca.explained_variance_)


array([4.73243698, 2.51108093, 1.45424187, 0.92416587, 0.85804868])

In [15]:
pca.explained_variance_ratio_

array([0.36198848, 0.1920749 , 0.11123631, 0.0706903 , 0.06563294])

In [16]:
pca.explained_variance_ratio_.cumsum()

array([0.36198848, 0.55406338, 0.66529969, 0.73598999, 0.80162293])

In [17]:
# Let us investigate the performance of the models

from sklearn.tree import DecisionTreeClassifier
DT = DecisionTreeClassifier(max_depth=3)
DT.fit(wine_scaled,wine_y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=3,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [18]:
score = accuracy_score(wine_y, DT.predict(wine_scaled))
score

0.9775280898876404

In [19]:
from sklearn.tree import DecisionTreeClassifier
DT_pca = DecisionTreeClassifier(max_depth=3)
DT.fit(wine_pca,wine_y)

score = accuracy_score(wine_y, DT.predict(wine_pca))
score

0.9887640449438202